/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/current/{school}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current measurements for all deployed sensors in a school */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description School ID used to scope sensor access and data lookup. */
                    school: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current sensor measurements. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessedSensorData"][];
                    };
                };
                /** @description Authentication or privilege failure. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error while fetching current sensor data. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/current/{school}/{location_short}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current measurements for a specific deployed sensor in a school */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    school: string;
                    /** @description Sensor short location code, such as c2 or outdoor. */
                    location_short: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current sensor measurements filtered to one sensor. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessedSensorData"][];
                    };
                };
                /** @description Authentication or privilege failure. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error while fetching current sensor data. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/historical/{school}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a historical line chart for a school's deployed sensors */
        get: {
            parameters: {
                query?: {
                    /** @description Data type to plot. Defaults to AQI. */
                    dataType?: components["schemas"]["ChartDataTypeKey"];
                    /** @description Time aggregation level for the historical series. */
                    aggregationType?: "minute" | "hour" | "day" | "month" | "year";
                    startDate?: string;
                    endDate?: string;
                    /** @description Minutes after midnight in the school timezone. */
                    startTime?: number;
                    /** @description Minutes after midnight in the school timezone. */
                    endTime?: number;
                };
                header?: never;
                path: {
                    school: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historical chart payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoricalLineChart"];
                    };
                };
                /** @description Invalid chart parameters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication or privilege failure. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HeatIndexResult: {
            val: number;
            category: string | null;
            categoryIndex: number;
        };
        OverallAQIResult: {
            val: number | null;
            categoryIndex: number | null;
            category: string | null;
            majorPollutant: string;
        };
        SensorCoordinates: {
            latitude: number | null;
            longitude: number | null;
        };
        SensorInfo: {
            sensor_id: number;
            location_type: string;
            location_short: string;
            location_long: string;
            /** Format: date-time */
            last_seen: string | null;
            coordinates: components["schemas"]["SensorCoordinates"];
            sorting_id: number;
        };
        CurrentMeasurement: {
            /** Format: date-time */
            timestamp: string;
            temperature: number | null;
            rel_humidity: number | null;
            heat_index_C: components["schemas"]["HeatIndexResult"] | null;
            aqi: components["schemas"]["OverallAQIResult"];
            "pm2.5": number | null;
            pm10_raw: number | null;
        };
        ProcessedSensorData: {
            sensor: components["schemas"]["SensorInfo"];
            current: components["schemas"]["CurrentMeasurement"] | null;
        };
        /** @enum {string} */
        ChartDataTypeKey: "aqi" | "pm2.5" | "pm10_raw" | "co2" | "voc" | "temperature_C" | "pressure" | "rel_humidity" | "heat_index_C";
        GenericScalar: string | number | boolean;
        GenericObject: {
            [key: string]: unknown;
        };
        GenericArrayRow: (components["schemas"]["GenericScalar"] | components["schemas"]["GenericObject"] | (components["schemas"]["GenericScalar"] | components["schemas"]["GenericObject"])[])[];
        HistoricalLineChart: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            id: "0";
            /** @example Historical */
            title: string;
            /** @enum {string} */
            chartType: "LineChart";
            dataArray: components["schemas"]["GenericArrayRow"][];
            allowedDataTypes?: components["schemas"]["ChartDataTypeKey"][];
            selectedDataType?: components["schemas"]["ChartDataTypeKey"];
            options?: components["schemas"]["GenericObject"];
            control?: components["schemas"]["GenericObject"];
        };
        CalendarSubchartPoint: {
            /** Format: date */
            day: string;
            value: number;
            tooltip: string;
        };
        CalendarSubchart: {
            subchartTitle: string;
            subchartTitleShort: string;
            dataArray: components["schemas"]["CalendarSubchartPoint"][];
        };
        CalendarChart: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            id: "1";
            title: string;
            /** @enum {string} */
            chartType: "Calendar";
            subcharts: components["schemas"]["CalendarSubchart"][];
            allowedDataTypes?: components["schemas"]["ChartDataTypeKey"][];
            selectedDataType?: components["schemas"]["ChartDataTypeKey"];
            columns: (number | components["schemas"]["GenericObject"])[];
            options: components["schemas"]["GenericObject"];
        };
        CorrelationScatterChart: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            id: "5";
            title: string;
            /** @enum {string} */
            chartType: "ScatterChart";
            dataArray: components["schemas"]["GenericArrayRow"][];
            allowedDataTypes?: components["schemas"]["ChartDataTypeKey"][];
            selectedDataType?: components["schemas"]["ChartDataTypeKey"];
            selectedAxes: {
                vAxis: string;
                hAxis: string;
            };
            columns: (number | components["schemas"]["GenericObject"])[];
            options: components["schemas"]["GenericObject"];
        };
        ChartResponse: components["schemas"]["HistoricalLineChart"] | components["schemas"]["CalendarChart"] | components["schemas"]["CorrelationScatterChart"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
